config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :cards
  root 'store#index', as: 'store_index'
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product product
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  skip_before_action :authorize
  before_action :set_card, only: [:show, :edit, :update, :destroy]
  before_action :incorect_cart, except: :index

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy if @card.id == session[:card_id]
    session[:card_id] = nil
    respond_to do |format|
      format.html {redirect_to store_index_url,
                               notice: 'Your cart is currently empty'}
      format.js
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.fetch(:card, {})
    end

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'Invalid cart'
    end

    def incorect_cart
      redirect_to store_index_url, notice: 'Incorect Cart' if @card.id != session[:card_id]
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>
  <h2>Your Cart</h2>
  <table>
     <%= render(card.line_items) %>
    <tfoot>
    <tr>
      <th colspan="2">Total:</th>
      <td class="price"><%= number_to_currency(card.total_price) %></td>
    </tr>
    </tfoot>
  </table>
  <div class="actions">
    <%= button_to 'Empty cart', card,
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, remote: true %>
    <%= button_to 'Checkout',  new_order_path,
                  method: :get,
                  class: "checkout" if @order.nil?%>
  </div>
</article>

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
  <% end %>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%= render @card %>>
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>