config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :cards
  root 'store#index', as: 'store_index'
  resources :products do
    get :who_bought, on: :member
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books online Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main">
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
      <div class="play">
        <div class="time">
          TIME: <%= timepiece('Bucharest') %>
        </div>
        <% if @counter %>
          <div class="count">
            Count index: <%= @counter %>
          </div>
        <% end %>
      </div>
    </header>
    <section class="content">
      <nav class="side_nav">
        <% if @card %>
          <div id="card" class="cards">
            <%= render_if(@card && @card.line_items.any?, @card) %>
          </div>
        <% end %>
        <ul>
          <li><%= link_to 'Home', store_index_url %></li>
        </ul>
        <% if session[:user_id] %>
          <nav class="logged_in_nav">
            <ul>
              <li><%= link_to 'Orders', orders_path %></li>
              <li><%= link_to 'Products', products_path %></li>
              <li><%= link_to 'Users', users_path %></li>
              <li><%= button_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </nav>
        <% end %>
      </nav>
      <main class="<%=controller.controller_name %>">
        <%= yield %>
      </main>
    </section>
  </body>
</html>